spring:
  application:
    name: salonn-booking

  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=booking_system;integratedSecurity=true;encrypt=true;trustServerCertificate=true
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect